cars_test/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'contacts', to: 'pages#contacts'
  get 'about', to: 'pages#about'

  get 'search', to: 'cars#search' 
  get 'list', to: 'cars#list'
  get 'data', to: 'cars#data'
  get 'distinct', to: 'cars#distinct'

  resources :cars

end

cars_test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cars_test/app/models/car.rb
class Car < ApplicationRecord

    validates :make, presence: true
    validates :fuel, presence: true
    validates :inspection, presence: true
    validates :score, presence: true


    def self.populate_database(lines_to_read)

        path = "/home/me/Ruby On Rails/rails-treinings-data/test_data/ta2020e.lst"
        if File.exists?(path)
            puts "File found"
        end

        File.open(path).each_with_index do |line, index|
            next if index == 0 
            break if index == lines_to_read #limiting amount of data to be read                                   
            args = line.split(',')   

            car_to_save = Car.new({
            make: args[1].strip.upcase,
            fuel: args[2].strip.upcase,
            inspection: args[3].strip.upcase,
            score: args[4].strip.upcase
            })

            car_to_save.save if car_to_save.valid?
            # could log or count how many records were not saved
        end
    end



    # DB query methods
    def self.search(params) 
        Car.where('make LIKE ? AND make LIKE ? AND fuel = ?', 
            "%#{params[:make].upcase}%", "%#{params[:model].upcase}%", "#{params[:fuel].upcase}")
    end

    def self.search_make(params) 
        Car.where('make LIKE ?', "%#{params[:make].upcase}%")
    end

    def self.search_make_dist
        Car.select(:make).distinct
    end

    def self.get_fuel_types
        fuel_types = []
        (Car.select(:fuel).distinct).each do |car|
            fuel_types.push(car[:fuel])
        end
        return fuel_types
    end



    # Calculation of AUTOSTATUS score - calculate weighted average value 
    def self.weighted_average(list) 
        scores = [0,0,0,0]
        list.each do |car| 
            scores[car[:score].to_i] += 1
        end
        average = (scores[1].to_f + (scores[2]*2).to_f + (scores[3]*3).to_f) / list.size
    end



    # Methods for calculating data for graphs
    def self.graph_data_basic(list)    
        scores = [[0, 0], [1, 0], [2, 0], [3, 0]] #not the most gracefull way, but might be faster than creating additional loop
        list.each do |car| 
            if car[:inspection].eql?("PAMATPĀRBAUDE")
                scores[car[:score].to_i][1] += 1 
            end
        end
        return scores
    end

    def self.graph_data_repeated(list) 
        scores = [[0, 0], [1, 0], [2, 0], [3, 0]]
        list.each do |car| 
            if car[:inspection].eql?("ATKĀRTOTA")
                scores[car[:score].to_i][1] += 1 
            end
        end
        return scores
    end

    def self.chart_max(values) # calculates y axis max value rounded down to 10s
        max = 0
        values.each do |value_pair|
            max = value_pair[1] if max < value_pair[1]
        end
        max /= 10 # drops the last digit
        max = (max*10)+10

    end

end

cars_test/app/models/image_scraper.rb
class ImageScraper < ApplicationRecord

    require "httparty"
    require "nokogiri"
    
    def self.get_image(make, model)
        
        # This block gets flickr.com search page, parses html and gets .photo-list-photo-view elements
        response = HTTParty.get("https://flickr.com/search/?text=#{make}%20#{model}") 
        parsed_html = Nokogiri::HTML(response.body) 
        car_photos = parsed_html.css(".photo-list-photo-view") 
        
        # Next get first element of .photo-list-photo-view class and get style atribute
        # Cant figure out how to get further than this using httparty and nokogiri, because of this use string methods
        photo_attributes = []  
        car_photos.each_with_index do |car, index|      
            break if index >= 1
            photo_attributes.push(car.attribute("style").value) 
        end
        
        # Spliting element by ';' gets last element, matches for 'url' ands cuts out url for image
        # Should probably use regex and not split in the first place
        info_string = photo_attributes.first.split(';').last 
        offset = info_string.index('url') 
        url_string = info_string[(6+offset)..-2] 
        return "https://#{url_string}"
    end

end

cars_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cars_test/app/controllers/cars_controller.rb
class CarsController < ApplicationController

    def index
    end

    def search

        # Should probably create search object and pass params to it and make validations etc. in it, - would help with this clutter
        # @search_string = params.inspect # for troubleshooting

        if params[:make].present? && (params[:only_make].to_i == 1)
            @list = Car.search_make(params)
            if  @list.count == 0
                redirect_to request.referrer, notice: "Nekas netika atrasts!"
            else
                params[:model] = "visi"
                params[:fuel] = "visi"
                @average = Car.weighted_average(@list)
                @graph_data_basic = Car.graph_data_basic(@list)
                @graph_data_repeated = Car.graph_data_repeated(@list)
                @chart_max = Car.chart_max(@graph_data_basic)
                @thumbnail_url = ImageScraper.get_image(params[:make], "pictures")
            end
        elsif params[:make].present? && params[:model].present? && params[:fuel].present? && (params[:only_make].to_i == 0)
            @list = Car.search(params)
            if  @list.count == 0
                redirect_to request.referrer, notice: "Nekas netika atrasts!"
            else
                @average = Car.weighted_average(@list)
                @graph_data_basic = Car.graph_data_basic(@list)
                @graph_data_repeated = Car.graph_data_repeated(@list)
                @chart_max = Car.chart_max(@graph_data_basic)
                @thumbnail_url = ImageScraper.get_image(params[:make], params[:model])
            end
        else
            redirect_to request.referrer, 
                notice: "Jāaizpilda visi atlases kritēriju lauki, vai jāievada auto ražotājs un jāatzīmē kritērijs: Atlasīt tikai pēc auto ražotāja!"
        end

    end

    def list
        if ((params[:model] == "visi") && (params[:fuel] == "visi"))
            @count = Car.search_make(params).count
            @list = Car.search_make(params).page(params[:page]).per(10)
        else
            @count = Car.search(params).count
            @list = Car.search(params).page(params[:page]).per(10)
        end
    end

    def data
        @cars = Car.page(params[:page]).per(10)
    end

    def distinct
        @count = Car.search_make_dist.order(:make).count
        @cars = Car.search_make_dist.order(:make).page(params[:page]).per(10)
    end

end

cars_test/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def contacts
    end

    def about
    end

end

cars_test/app/helpers/application_helper.rb
module ApplicationHelper
end

cars_test/app/helpers/cars_helper.rb
module CarsHelper
end

cars_test/app/helpers/pages_helper.rb
module PagesHelper
end

cars_test/app/views/cars/_troubleshooting.html.erb
<div class="row">
    <p>Returned search data for : <br><b><%= @search_string %></b></p> 
    <h4>Kopējais atlasīto ierakstu skaits : <%= @list.count %></h4> <br>
</div>

cars_test/app/views/cars/data.html.erb
<div class="row">

    <div class="col-sm-4">
        <%= render 'layouts/search'%>
    </div>

    <div class="col-sm-8">

        <h3 class="text-center">APLIKĀCIJAS DATUBĀZĒ ŠOBRĪD IR : <b><%= Car.count %></b> IERAKSTI </h3>
        <h5 class="text-center">Sīkāku informāciju par datu ieguvi var apskatīt sadaļā: <a href="/about">PAR</a></h5><br>

        <table class="table table-striped">
                <thead>
                    <tr>
                        <th>RAŽOTĀJS / MODELIS</th>
                        <th>DEGVIELAS VEIDS</th>
                        <th>TA PĀRBAUDES VEIDS</th>
                        <th>REZULTĀTS</th>
                    </tr>
                </thead>
            <tbody>
                    <% @cars.each_with_index do |car, index| %>
                        <% break if index > 50 %>
                        <tr>
                            <td><%= car.make %></td>
                            <td><%= car.fuel %></td>
                            <td><%= car.inspection %></td>
                            <td><%= car.score %></td>
                        </tr>
                    <% end %>
            </tbody>
        </table>

        <div class="col-sm-2"></div>
        <div class="col-sm-8 text-center paginate"><p><%= paginate @cars %></p></div>
        <div class="col-sm-2"></div>
        
    </div>

</div>

cars_test/app/views/cars/distinct.html.erb
<div class="row">

    <div class="col-sm-4">
        <%= render 'layouts/search'%>
    </div>

    <div class="col-sm-8">

        <h3 class="text-center">UNIKĀLO RAŽOTĀJA/MODEĻA PĀRU SKAITS : <b><%= @count %></b> IERAKSTI </h3>
        <h4 class="text-center">Aplūkot unikālos auto modeļus, kas ir datubāzē, var: <a href="/distinct">ŠEIT</a></h4>
        <h5 class="text-center">Sīkāku informāciju par datu ieguvi var apskatīt sadaļā: <a href="/about">PAR</a></h5><br>

        <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">RAŽOTĀJS / MODELIS</th>
                    </tr>
                </thead>
            <tbody>
                    <% @cars.each_with_index do |car, index| %>
                        <% break if index > 50 %>
                        <tr>
                            <td class="text-center"><%= car.make %></td>
                        </tr>
                    <% end %>
            </tbody>
        </table>

        <div class="col-sm-2"></div>
        <div class="col-sm-8 text-center paginate"><p><%= paginate @cars %></p></div>
        <div class="col-sm-2"></div>
        
    </div>

</div>

cars_test/app/views/cars/index.html.erb
<div class="row">

    <div class="col-sm-4">
      <%= render 'layouts/search'%>
    </div>

    <div class="col-sm-8">
      <h3 class="text-center"><strong>Kā izmantot AUTO STATUSS meklēšanas rīku?</strong></h3><br><br>
      <%= image_tag "graph.jpg", class: "img-responsive "%> 
    </div>

</div>

cars_test/app/views/cars/list.html.erb
<div class="row">

    <div class="col-sm-4">
        <%= render 'layouts/search'%>
    </div>

    <div class="col-sm-8">

        <h3 class="text-center">ATLASĪTO AUTO SKAITS : <b><%= @count %></b> IERAKSTI </h3><br>

        <table class="table table-striped">
                <thead>
                    <tr>
                        <th>RAŽOTĀJS / MODELIS</th>
                        <th>DEGVIELAS VEIDS</th>
                        <th>TA PĀRBAUDES VEIDS</th>
                        <th>REZULTĀTS</th>
                    </tr>
                </thead>
            <tbody>
                    <% @list.each_with_index do |car, index| %>
                        <% break if index > 50 %>
                        <tr>
                            <td><%= car.make %></td>
                            <td><%= car.fuel %></td>
                            <td><%= car.inspection %></td>
                            <td><%= car.score %></td>
                        </tr>
                    <% end %>
            </tbody>
        </table>

        <div class="col-sm-2"></div>
        <div class="col-sm-8 text-center paginate"><p><%= paginate @list %></p></div>
        <div class="col-sm-2"></div>

    </div>

</div>

cars_test/app/views/cars/search.html.erb
<div class="row">

    <div class="col-sm-4">
        <%= render 'layouts/search'%>   
    </div>

    <div class="col-sm-8">

        <div class="row">
            <div class="col-sm-4">
                <div>
                <br>
                <img src="<%=@thumbnail_url%>" class="img-thumbnail">
                </div>
            </div>
            <div class="col-sm-6">
                <h3>Meklētais auto:</h3>
                <p>Ražotājs: <strong><%= params[:make].upcase %></strong></p>
                <p>Modelis: <strong><%= params[:model].upcase %></strong></p>
                <p>Degvielas tips: <strong><%= params[:fuel].upcase %></strong></p>
                <p>Kopējais auto skaits pēc atlases kritērijiem: <strong class="seems-18px"><%= @list.count %></strong></p>
                <h4><strong>AUTO STATUSS:</strong><strong class="text-success"> <%= sprintf('%.2f', @average) %></strong></h4>
            </div > 
            <div class="col-sm-2 relative"><br>
                <%= link_to "ATLASĪTIE IERAKSTI", list_path(make: params[:make], model: params[:model], fuel: params[:fuel]), class: "btn btn-primary"%>
            </div>  
        </div><br>

        <div class="row border-top"><br>
            <%= render 'layouts/car_graphs'%>
        </div>

    </div>

</div>

cars_test/app/views/layouts/_car_graphs.html.erb
<div class="col-sm-5">
    <h4 class="text-center">Pamatpārbaužu rezultāti</h4>
    <%= column_chart @graph_data_basic, colors: ["#32cd32"],
        xtitle: "Vērtējums", ytitle: "Rezultātu skaits", max: @chart_max%>
</div>
<div class="col-sm-5">
    <h4 class="text-center">Atkārtoto pārbaužu rezultāti</h4>
    <%= column_chart @graph_data_repeated, colors: ["#FFD700"], 
        xtitle: "Vērtējums", ytitle: "Rezultātu skaits", max: @chart_max %>
</div>

cars_test/app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    Ruby on Rails treinings 2021
  </small>

  <nav>
    <ul>
      <li><%= link_to "DATUBĀZES DATI", data_path%></li>
      <li><%= link_to "KONTAKTI", contacts_path%></li>
    </ul>
  </nav>

</footer>

cars_test/app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

      <div class="navbar-header">
        <a class="navbar-brand" href="/"><strong>AUTO STATUSS</strong></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "SĀKUMS", root_path%></li>
        <li><%= link_to "AUTO STATUSS", cars_path%></li>
        <li><%= link_to "PAR", about_path%></li>
      </ul>

    </div>
  </nav>

</header>

cars_test/app/views/layouts/_search.html.erb
<div class="row">
    <div class="col-sm-1"></div>

    <div class="col-sm-8">
        <br>
        <%= form_with url: "/search", method: :get do |form| %>
            <p>
            <%= form.label :make, "Ražotājs" %><br>
            <%= form.text_field :make, class: 'form-control'%>
            </p>

            <p>
            <%= form.label :model, "Modelis" %><br>
            <%= form.text_field :model, class: 'form-control' %>
            </p>
            
            <%= form.label :fuel, "Degviela" %><br>
            <select id="fuel" name="fuel" class="form-control">
                <option value="" ></option>
                <% Car.get_fuel_types.each do |fuel| %>
                    <option value="<%=fuel%>"><%=fuel%></option>
                <% end%>
            </select><br>

            <p>
            <%= form.check_box :only_make %>
            <%= form.label :only_make, "Atlasīt tikai pēc ražotāja" %><br>
            </p>            

            <p>
            <%= form.submit "ATLASĪT", class: 'form-control btn-primary' %>
            </p>
        <% end %>
    </div>

</div>

cars_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auto Statuss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>

    <div class="container">

      <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
        <b><%= msg %></b>
        </div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>

    </div class="container">
    
  </body>
</html>

cars_test/app/views/pages/about.html.erb
<div class="jumbotron">

    <div class="row">
        <div class="col-sm-3"></div>

        <div class="col-sm-6 matt text-center">
            <br>

            <h3 class="text-center"><strong>PAR APLIKĀCIJU</strong><h3>
            <h5 class="text-justify"> Applikācijā izmantoti brīvpiekļuves dati, kas publicēti Latvijas Atvērto datu portālā par 
                VAS Ceļu Satiksmes Drošības Direkcijas veiktajām auto tehniskajām apskatēm 2020. gadā.</h5>
            <h5 class="text-justify text-center">AUTO STATUSS koeficients ir rēķināts, kā vidējais svērtais lielums 
                starp TA iegūto rezultātu un auto skaitu. Formulu skatīt zemāk</h5>
            <h5>Zemāk tabulā pieejama papildus informācija un saites uz informācijas avotiem.</h5>

            <table class="table table-hover table-condensed">
                <tbody> 
                    <tr>                            
                        <td class="text-left"><b>Latvijas Atvērto datu portāls</b></td>
                        <td><b><a href="https://data.gov.lv/lv">www.data.gov.lv</a></b></td>
                    </tr>
                    <tr>                            
                        <td class="text-left"><b>Ceļu Satiksmes Drošības direkcija</b></td>
                        <td><b><a href="https://www.csdd.lv/">www.csdd.lv</a></b></td>
                    </tr> 
                    <tr>                            
                        <td class="text-left"><b>Izmantotā datu kopa</b></td>
                        <td><b><a href="https://data.gov.lv/dati/lv/dataset/tehniskas-apskates/resource/655910f4-c614-4ea4-9360-7a5e6ad81aef">Tehniskās apskates 2020. gadā</a></b></td>
                    </tr> 
                    <tr>                            
                        <td class="text-left"><b>Pēdējo reizi dati atjaunoti</b></td>
                        <td>30.07.2021</td>
                    </tr> 
                    <tr>                            
                        <td class="text-left"><b>Datu formāts</b></td>
                        <td>.csv</td>
                    </tr> 
                    <tr>                            
                        <td class="text-left"><b>Datu atjaunošanas biežums</b></td>
                        <td>Reizi gadā</td>
                    </tr> 
                    <tr>                            
                        <td class="text-left"><b>AUTO STATUSS aprēķins: </b></td>
                        <td>x = (x<sub>1</sub> + (x<sub>2</sub> &times n<sub>2</sub>) + (x<sub>2</sub> &times n<sub>3</sub>)) / n<sub>sum(0..3)</sub></td>
                    </tr>  
                </tbody>
            </table>
            
        </div>

        <div class="col-sm-3"></div>
    </div>

</div>

cars_test/app/views/pages/contacts.html.erb
<div class="jumbotron">

    <div class="row">
        <div class="col-sm-3"></div>

        <div class="col-sm-6 matt text-center"><br>
            <h3 class="text-center"><strong>APLIKĀCIJA MĀJO:</strong><h3>
            <a href="https://github.com/KakaransE/rails-treinings" class="btn btn-primary" role="button">GITHUB</a><br>
        </div>

        <div class="col-sm-3"></div>
    </div>

</div>

cars_test/app/views/pages/home.html.erb
<div class="jumbotron">

    <div class="row">
        <div class="col-sm-3"></div>

        <div class="col-sm-6 matt"><br>
            <h1 class="text-center home-title"><b>AUTO STATUSS</b></h1> <br> <br>
            <h4 class="spacing home-text text-justify"><b>AUTO STATUSS IR APLIKĀCIJA, KAS DOD IESPĒJU, VISIEM LATVIJAS IEDZĪVOTĀJIEM, IEPAZĪTIES AR LATVIJAS 
                REPUBLIKĀ REĢISTRĒTO AUTO STĀVOKLI.</b></h4>
            <h5 class="spacing home-text text-center">JUMS IR IESPĒJA IEVADĪT INTERESĒJOŠO AUTO RŽOTĀJU, MODELI UN IZVĒLĒTIES TĀ DEGVIELAS VEIDU.</h5> <br>
            <%= button_to "UZ AUTO ATLASI", cars_path, method: :get, class: 'btn btn-primary form-control'%><br>
        </div>

        <div class="col-sm-3"></div>
    </div>

</div>